### ISSUE TITLE
Shall we build it using the Django framework?

### ISSUE THREAD

**Issue by RajuKoushik** [iiitv/hackathon-team-builder#1]
@singhpratyush  Should I work on this right away with the discussed models so that we can move on to the views later.Cheers.

**Comment by singhpratyush** [comment]
Yes. But first we have to decide the different apps that we will need. I think that `participant` and `team` would do in addition to `home`. Any views?

**Comment by RajuKoushik** [comment]
Did you mean 3 views (participant,team,home) in a single django app ? I think a single app would be sufficient with the above three modules.

**Comment by singhpratyush** [comment]
I meant 3 django apps.

**Comment by singhpratyush** [comment]
Fine then. I'll start a new app and create models. Will start working on views later on.
