### ISSUE TITLE
Changes in skill model

### ISSUE THREAD

**Issue by arpit1997** [iiitv/hackathon-team-builder#12]
In `Skill ` model instead of using limited skill fields like back_end, front_end we an use a [JSONField](https://github.com/bradjasper/django-jsonfield) as `{'skill':'level'}`.

**Comment by yashLadha** [comment]
A team member must select anyone from frontend, backend, tester, presenter, manager only. No other field should be specified by the user ( participant ).

**Comment by arpit1997** [comment]
Thanks for clarification. Closing issue #12 now.
